# Site settings
title: Optika Adria | Okulistične specialistične ambulante
email: adriaplast@adriaplast.si
tel: '+386 56 776740'
description: > # this means to ignore newlines until "baseurl:"
  Sončna očala, Korekcijska očala, Kontaktne leče. Vaš optik na območju države Slovenia. Adria Optika samo najboljše za vaše oči.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.adriaoptika.si"

# Build settings
markdown: kramdown
