# Site settings
title: adria · optika
email: adriaplast@adriaplast.si
tel: '+386 56 776740'
description: > # this means to ignore newlines until "baseurl:"
  Adria Optika samo najboljše za vaše oči.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.adriaoptika.si"

# Build settings
markdown: kramdown
